name: Setup Environment Action
description: "Setup the environment for the CI"

inputs:
  os:
    description: "CI environment"
    required: true

runs:
  using: "composite"
  steps:
    - name: Setup python
      uses: actions/setup-python@v5
      with:
        python-version: "3.10"
        cache: "pip"

    - name: Install Python Requiremetns
      shell: bash
      run: pip install .

    - name: Install APT packages
      shell: bash
      run: |
        sudo apt-get update
        xargs -a .github/workflows/apt-dependencies.txt sudo apt-get install -y

    - name: mkdir
      shell: bash
      run: mkdir -p ~/nvc

    - name: cache-nvc
      id: cache-nvc
      uses: actions/cache@v4
      with:
        path: ~/nvc
        key: ${{ runner.os }}-nvc-r1.18.1

    - name: Build NVC if not cached
      if: steps.cache-nvc.outputs.cache-hit != 'true'
      shell: bash
      run: |
        git clone https://github.com/nickg/nvc.git ~/nvc
        cd ~/nvc
        git checkout r1.18.1
        ./autogen.sh
        mkdir build && cd build
        ../configure
        make

    - name: Install NVC
      shell: bash
      run: |
        cd ~/nvc/build
        sudo make install
