-- Generated by PeakRDL-regblock-vhdl - A free and open-source VHDL generator
--  https://github.com/SystemRDL/PeakRDL-regblock-vhdl
library ieee;
context ieee.ieee_std_context;
use ieee.fixed_pkg.all;

use work.regblock_pkg.all;
use work.reg_utils.all;

entity regblock is
    port (
        clk : in std_logic;
        arst : in std_logic;

        s_axil_awready : out std_logic;
        s_axil_awvalid : in std_logic;
        s_axil_awaddr : in std_logic_vector(7 downto 0);
        s_axil_awprot : in std_logic_vector(2 downto 0);
        s_axil_wready : out std_logic;
        s_axil_wvalid : in std_logic;
        s_axil_wdata : in std_logic_vector(31 downto 0);
        s_axil_wstrb : in std_logic_vector(3 downto 0);
        s_axil_bready : in std_logic;
        s_axil_bvalid : out std_logic;
        s_axil_bresp : out std_logic_vector(1 downto 0);
        s_axil_arready : out std_logic;
        s_axil_arvalid : in std_logic;
        s_axil_araddr : in std_logic_vector(7 downto 0);
        s_axil_arprot : in std_logic_vector(2 downto 0);
        s_axil_rready : in std_logic;
        s_axil_rvalid : out std_logic;
        s_axil_rdata : out std_logic_vector(31 downto 0);
        s_axil_rresp : out std_logic_vector(1 downto 0);

        hwif_in : in regblock_in_t;
        hwif_out : out regblock_out_t
    );
end entity regblock;

architecture rtl of regblock is
    ----------------------------------------------------------------------------
    -- CPU Bus interface signals
    ----------------------------------------------------------------------------
    signal cpuif_req : std_logic;
    signal cpuif_req_is_wr : std_logic;
    signal cpuif_addr : std_logic_vector(7 downto 0);
    signal cpuif_wr_data : std_logic_vector(31 downto 0);
    signal cpuif_wr_biten : std_logic_vector(31 downto 0);
    signal cpuif_req_stall_wr : std_logic;
    signal cpuif_req_stall_rd : std_logic;

    signal cpuif_rd_ack : std_logic;
    signal cpuif_rd_err : std_logic;
    signal cpuif_rd_data : std_logic_vector(31 downto 0);

    signal cpuif_wr_ack : std_logic;
    signal cpuif_wr_err : std_logic;

    signal cpuif_req_masked : std_logic;

    signal axil_n_in_flight : unsigned(1 downto 0);
    signal axil_prev_was_rd : std_logic;
    signal axil_arvalid : std_logic;
    signal axil_araddr : std_logic_vector(7 downto 0);
    signal axil_ar_accept : std_logic;
    signal axil_awvalid : std_logic;
    signal axil_awaddr : std_logic_vector(7 downto 0);
    signal axil_wvalid : std_logic;
    signal axil_wdata : std_logic_vector(31 downto 0);
    signal axil_wstrb : std_logic_vector(3 downto 0);
    signal axil_aw_accept : std_logic;
    signal axil_resp_acked : std_logic;
    type axil_resp_buffer_t is record
        is_wr : std_logic;
        err : std_logic;
        rdata : std_logic_vector(31 downto 0);
    end record axil_resp_buffer_t;
    type axil_resp_buffer_array_t is array (integer range <>) of axil_resp_buffer_t;
    signal axil_resp_buffer : axil_resp_buffer_array_t(1 downto 0);
    signal axil_resp_wptr : unsigned(1 downto 0);
    signal axil_resp_rptr : unsigned(1 downto 0);

    ----------------------------------------------------------------------------
    -- Address Decode Signals
    ----------------------------------------------------------------------------
    type decoded_reg_strb_t is record
        git_hash : std_logic;
        git_status : std_logic;
        fpga_id : std_logic;
        spi_tx_data : std_logic;
        spi_rx_data : std_logic;
        vga_color : std_logic;
        switch_status : std_logic;
        bad_address_counter : std_logic;
        test_register_1 : std_logic;
        test_register_2 : std_logic;
    end record;
    signal decoded_reg_strb : decoded_reg_strb_t;
    signal decoded_err : std_logic;
    signal decoded_addr : std_logic_vector(7 downto 0);
    signal decoded_req : std_logic;
    signal decoded_req_is_wr : std_logic;
    signal decoded_wr_data : std_logic_vector(31 downto 0);
    signal decoded_wr_biten : std_logic_vector(31 downto 0);

    ----------------------------------------------------------------------------
    -- Field Logic Signals
    ----------------------------------------------------------------------------
    -- Field Combinational Signals
    type \regblock.spi_tx_data.tx_data_combo_t\ is record
        next_q : std_logic_vector(7 downto 0);
        load_next : std_logic;
    end record;

    type \regblock.spi_tx_data_combo_t\ is record
        tx_data : \regblock.spi_tx_data.tx_data_combo_t\;
    end record;

    type \regblock.spi_rx_data.rx_data_combo_t\ is record
        next_q : std_logic_vector(7 downto 0);
        load_next : std_logic;
    end record;

    type \regblock.spi_rx_data_combo_t\ is record
        rx_data : \regblock.spi_rx_data.rx_data_combo_t\;
    end record;

    type \regblock.vga_color.blue_combo_t\ is record
        next_q : std_logic_vector(3 downto 0);
        load_next : std_logic;
    end record;

    type \regblock.vga_color.green_combo_t\ is record
        next_q : std_logic_vector(3 downto 0);
        load_next : std_logic;
    end record;

    type \regblock.vga_color.red_combo_t\ is record
        next_q : std_logic_vector(3 downto 0);
        load_next : std_logic;
    end record;

    type \regblock.vga_color_combo_t\ is record
        blue : \regblock.vga_color.blue_combo_t\;
        green : \regblock.vga_color.green_combo_t\;
        red : \regblock.vga_color.red_combo_t\;
    end record;

    type \regblock.bad_address_counter.count_combo_t\ is record
        next_q : std_logic_vector(31 downto 0);
        load_next : std_logic;
        incrthreshold : std_logic;
        overflow : std_logic;
    end record;

    type \regblock.bad_address_counter_combo_t\ is record
        count : \regblock.bad_address_counter.count_combo_t\;
    end record;

    type \regblock.test_register_1.test_bits_combo_t\ is record
        next_q : std_logic_vector(31 downto 0);
        load_next : std_logic;
    end record;

    type \regblock.test_register_1_combo_t\ is record
        test_bits : \regblock.test_register_1.test_bits_combo_t\;
    end record;

    type \regblock.test_register_2.test_bits_combo_t\ is record
        next_q : std_logic_vector(31 downto 0);
        load_next : std_logic;
    end record;

    type \regblock.test_register_2_combo_t\ is record
        test_bits : \regblock.test_register_2.test_bits_combo_t\;
    end record;

    type field_combo_t is record
        spi_tx_data : \regblock.spi_tx_data_combo_t\;
        spi_rx_data : \regblock.spi_rx_data_combo_t\;
        vga_color : \regblock.vga_color_combo_t\;
        bad_address_counter : \regblock.bad_address_counter_combo_t\;
        test_register_1 : \regblock.test_register_1_combo_t\;
        test_register_2 : \regblock.test_register_2_combo_t\;
    end record;
    signal field_combo : field_combo_t;

    -- Field Storage Signals
    type \regblock.spi_tx_data.tx_data_storage_t\ is record
        value : std_logic_vector(7 downto 0);
    end record;

    type \regblock.spi_tx_data_storage_t\ is record
        tx_data : \regblock.spi_tx_data.tx_data_storage_t\;
    end record;

    type \regblock.spi_rx_data.rx_data_storage_t\ is record
        value : std_logic_vector(7 downto 0);
    end record;

    type \regblock.spi_rx_data_storage_t\ is record
        rx_data : \regblock.spi_rx_data.rx_data_storage_t\;
    end record;

    type \regblock.vga_color.blue_storage_t\ is record
        value : std_logic_vector(3 downto 0);
    end record;

    type \regblock.vga_color.green_storage_t\ is record
        value : std_logic_vector(3 downto 0);
    end record;

    type \regblock.vga_color.red_storage_t\ is record
        value : std_logic_vector(3 downto 0);
    end record;

    type \regblock.vga_color_storage_t\ is record
        blue : \regblock.vga_color.blue_storage_t\;
        green : \regblock.vga_color.green_storage_t\;
        red : \regblock.vga_color.red_storage_t\;
    end record;

    type \regblock.bad_address_counter.count_storage_t\ is record
        value : std_logic_vector(31 downto 0);
    end record;

    type \regblock.bad_address_counter_storage_t\ is record
        count : \regblock.bad_address_counter.count_storage_t\;
    end record;

    type \regblock.test_register_1.test_bits_storage_t\ is record
        value : std_logic_vector(31 downto 0);
    end record;

    type \regblock.test_register_1_storage_t\ is record
        test_bits : \regblock.test_register_1.test_bits_storage_t\;
    end record;

    type \regblock.test_register_2.test_bits_storage_t\ is record
        value : std_logic_vector(31 downto 0);
    end record;

    type \regblock.test_register_2_storage_t\ is record
        test_bits : \regblock.test_register_2.test_bits_storage_t\;
    end record;

    type field_storage_t is record
        spi_tx_data : \regblock.spi_tx_data_storage_t\;
        spi_rx_data : \regblock.spi_rx_data_storage_t\;
        vga_color : \regblock.vga_color_storage_t\;
        bad_address_counter : \regblock.bad_address_counter_storage_t\;
        test_register_1 : \regblock.test_register_1_storage_t\;
        test_register_2 : \regblock.test_register_2_storage_t\;
    end record;
    signal field_storage : field_storage_t;

    ----------------------------------------------------------------------------
    -- Readback Signals
    ----------------------------------------------------------------------------
    signal rd_mux_addr : unsigned(7 downto 0);
    signal readback_err : std_logic;
    signal readback_done : std_logic;
    signal readback_data : std_logic_vector(31 downto 0);
begin

    ----------------------------------------------------------------------------
    -- CPU Bus interface
    ----------------------------------------------------------------------------
    

    -- Max Outstanding Transactions: 2
    -- Transaction request acceptance
    process(clk, arst) begin
        if arst then -- async reset
            axil_prev_was_rd <= '0';
            axil_arvalid <= '0';
            axil_araddr <= (others => '0');
            axil_awvalid <= '0';
            axil_awaddr <= (others => '0');
            axil_wvalid <= '0';
            axil_wdata <= (others => '0');
            axil_wstrb <= (others => '0');
            axil_n_in_flight <= (others => '0');
        elsif rising_edge(clk) then
            if false then -- sync reset
                axil_prev_was_rd <= '0';
                axil_arvalid <= '0';
                axil_araddr <= (others => '0');
                axil_awvalid <= '0';
                axil_awaddr <= (others => '0');
                axil_wvalid <= '0';
                axil_wdata <= (others => '0');
                axil_wstrb <= (others => '0');
                axil_n_in_flight <= (others => '0');
            else
                -- AR* acceptance register
                if axil_ar_accept then
                    axil_prev_was_rd <= '1';
                    axil_arvalid <= '0';
                end if;
                if s_axil_arvalid and s_axil_arready then
                    axil_arvalid <= '1';
                    axil_araddr <= s_axil_araddr;
                end if;

                -- AW* & W* acceptance registers
                if axil_aw_accept  then
                    axil_prev_was_rd <= '0';
                    axil_awvalid <= '0';
                    axil_wvalid <= '0';
                end if;
                if s_axil_awvalid and s_axil_awready then
                    axil_awvalid <= '1';
                    axil_awaddr <= s_axil_awaddr;
                end if;
                if s_axil_wvalid and s_axil_wready then
                    axil_wvalid <= '1';
                    axil_wdata <= s_axil_wdata;
                    axil_wstrb <= s_axil_wstrb;
                end if;

                -- Keep track of in-flight transactions
                if (axil_ar_accept or axil_aw_accept) and not axil_resp_acked then
                    axil_n_in_flight <= axil_n_in_flight + 1;
                elsif not (axil_ar_accept or axil_aw_accept) and axil_resp_acked then
                    axil_n_in_flight <= axil_n_in_flight - 1;
                end if;
            end if;
        end if;
    end process;

    process(all) begin
        s_axil_arready <= not axil_arvalid or axil_ar_accept;
        s_axil_awready <= not axil_awvalid or axil_aw_accept;
        s_axil_wready <= not axil_wvalid or axil_aw_accept;
    end process;

    -- Request dispatch
    process(all) begin
        cpuif_wr_data <= axil_wdata;
        for i in axil_wstrb'RANGE loop
            cpuif_wr_biten(i*8 + 7 downto i*8) <= (others => axil_wstrb(i));
        end loop;
        cpuif_req <= '0';
        cpuif_req_is_wr <= '0';
        cpuif_addr <= (others => '0');
        axil_ar_accept <= '0';
        axil_aw_accept <= '0';

        if axil_n_in_flight < to_unsigned(2, 2) then
            -- Can safely issue more transactions without overwhelming response buffer
            if axil_arvalid and not axil_prev_was_rd then
                cpuif_req <= '1';
                cpuif_req_is_wr <= '0';
                cpuif_addr <= (7 downto 2 => axil_araddr(7 downto 2), others => '0');
                if not cpuif_req_stall_rd then
                    axil_ar_accept <= '1';
                end if;
            elsif axil_awvalid and axil_wvalid then
                cpuif_req <= '1';
                cpuif_req_is_wr <= '1';
                cpuif_addr <= (7 downto 2 => axil_awaddr(7 downto 2), others => '0');
                if not cpuif_req_stall_wr then
                    axil_aw_accept <= '1';
                end if;
            elsif axil_arvalid then
                cpuif_req <= '1';
                cpuif_req_is_wr <= '0';
                cpuif_addr <= (7 downto 2 => axil_araddr(7 downto 2), others => '0');
                if not cpuif_req_stall_rd then
                    axil_ar_accept <= '1';
                end if;
            end if;
        end if;
    end process;
    -- AXI4-Lite Response Logic
    process(clk, arst) begin
        if arst then -- async reset
            for i in axil_resp_buffer'RANGE loop
                axil_resp_buffer(i).is_wr <= '0';
                axil_resp_buffer(i).err <= '0';
                axil_resp_buffer(i).rdata <= (others => '0');
            end loop;
            axil_resp_wptr <= (others => '0');
            axil_resp_rptr <= (others => '0');
        elsif rising_edge(clk) then
            if false then -- sync reset
                for i in axil_resp_buffer'RANGE loop
                    axil_resp_buffer(i).is_wr <= '0';
                    axil_resp_buffer(i).err <= '0';
                    axil_resp_buffer(i).rdata <= (others => '0');
                end loop;
                axil_resp_wptr <= (others => '0');
                axil_resp_rptr <= (others => '0');
            else
                -- Store responses in buffer until AXI response channel accepts them
                if cpuif_rd_ack or cpuif_wr_ack then
                    if cpuif_rd_ack then
                        axil_resp_buffer(to_integer(axil_resp_wptr(0 downto 0))).is_wr <= '0';
                        axil_resp_buffer(to_integer(axil_resp_wptr(0 downto 0))).err <= cpuif_rd_err;
                        axil_resp_buffer(to_integer(axil_resp_wptr(0 downto 0))).rdata <= cpuif_rd_data;

                    elsif cpuif_wr_ack then
                        axil_resp_buffer(to_integer(axil_resp_wptr(0 downto 0))).is_wr <= '1';
                        axil_resp_buffer(to_integer(axil_resp_wptr(0 downto 0))).err <= cpuif_wr_err;
                    end if;
                    axil_resp_wptr <= axil_resp_wptr + 1;
                end if;

                -- Advance read pointer when acknowledged
                if axil_resp_acked then
                    axil_resp_rptr <= axil_resp_rptr + 1;
                end if;
            end if;
        end if;
    end process;

    process(all) begin
        axil_resp_acked <= '0';
        s_axil_bvalid <= '0';
        s_axil_rvalid <= '0';
        if axil_resp_rptr /= axil_resp_wptr then
            if axil_resp_buffer(to_integer(axil_resp_rptr(0 downto 0))).is_wr then
                s_axil_bvalid <= '1';
                if s_axil_bready then
                    axil_resp_acked <= '1';
                end if;
            else
                s_axil_rvalid <= '1';
                if s_axil_rready then
                    axil_resp_acked <= '1';
                end if;
            end if;
        end if;

        s_axil_rdata <= axil_resp_buffer(to_integer(axil_resp_rptr(0 downto 0))).rdata;
        if axil_resp_buffer(to_integer(axil_resp_rptr(0 downto 0))).err then
            s_axil_bresp <= "10";
            s_axil_rresp <= "10";
        else
            s_axil_bresp <= "00";
            s_axil_rresp <= "00";
        end if;
    end process;


    -- Read & write latencies are balanced. Stalls not required
    cpuif_req_stall_rd <= '0';
    cpuif_req_stall_wr <= '0';
    cpuif_req_masked <= cpuif_req
                        and not (not cpuif_req_is_wr and cpuif_req_stall_rd)
                        and not (cpuif_req_is_wr and cpuif_req_stall_wr);

    ----------------------------------------------------------------------------
    -- Address Decode
    ----------------------------------------------------------------------------
    process(all)
        -- overload "=" in this scope to avoid lots of type casts
        function "="(L: std_logic_vector; R: integer) return std_logic is
            variable result : std_logic;
        begin
            result := '1' when unsigned(L) = R else '0';
            return result;
        end;
        variable is_valid_addr : std_logic;
        variable is_valid_rw : std_logic;
    begin
        is_valid_addr := '0';
        is_valid_rw := '0';
        decoded_reg_strb.git_hash <= cpuif_req_masked and (cpuif_addr = 16#0#) and not cpuif_req_is_wr;
        is_valid_addr := is_valid_addr or (cpuif_req_masked and (cpuif_addr = 16#0#));
        is_valid_rw := is_valid_rw or (cpuif_req_masked and (cpuif_addr = 16#0#) and not cpuif_req_is_wr);
        decoded_reg_strb.git_status <= cpuif_req_masked and (cpuif_addr = 16#4#) and not cpuif_req_is_wr;
        is_valid_addr := is_valid_addr or (cpuif_req_masked and (cpuif_addr = 16#4#));
        is_valid_rw := is_valid_rw or (cpuif_req_masked and (cpuif_addr = 16#4#) and not cpuif_req_is_wr);
        decoded_reg_strb.fpga_id <= cpuif_req_masked and (cpuif_addr = 16#8#) and not cpuif_req_is_wr;
        is_valid_addr := is_valid_addr or (cpuif_req_masked and (cpuif_addr = 16#8#));
        is_valid_rw := is_valid_rw or (cpuif_req_masked and (cpuif_addr = 16#8#) and not cpuif_req_is_wr);
        decoded_reg_strb.spi_tx_data <= cpuif_req_masked and (cpuif_addr = 16#C#);
        is_valid_addr := is_valid_addr or (cpuif_req_masked and (cpuif_addr = 16#C#));
        is_valid_rw := is_valid_rw or (cpuif_req_masked and (cpuif_addr = 16#C#));
        decoded_reg_strb.spi_rx_data <= cpuif_req_masked and (cpuif_addr = 16#10#) and not cpuif_req_is_wr;
        is_valid_addr := is_valid_addr or (cpuif_req_masked and (cpuif_addr = 16#10#));
        is_valid_rw := is_valid_rw or (cpuif_req_masked and (cpuif_addr = 16#10#) and not cpuif_req_is_wr);
        decoded_reg_strb.vga_color <= cpuif_req_masked and (cpuif_addr = 16#14#);
        is_valid_addr := is_valid_addr or (cpuif_req_masked and (cpuif_addr = 16#14#));
        is_valid_rw := is_valid_rw or (cpuif_req_masked and (cpuif_addr = 16#14#));
        decoded_reg_strb.switch_status <= cpuif_req_masked and (cpuif_addr = 16#18#) and not cpuif_req_is_wr;
        is_valid_addr := is_valid_addr or (cpuif_req_masked and (cpuif_addr = 16#18#));
        is_valid_rw := is_valid_rw or (cpuif_req_masked and (cpuif_addr = 16#18#) and not cpuif_req_is_wr);
        decoded_reg_strb.bad_address_counter <= cpuif_req_masked and (cpuif_addr = 16#1C#) and not cpuif_req_is_wr;
        is_valid_addr := is_valid_addr or (cpuif_req_masked and (cpuif_addr = 16#1C#));
        is_valid_rw := is_valid_rw or (cpuif_req_masked and (cpuif_addr = 16#1C#) and not cpuif_req_is_wr);
        decoded_reg_strb.test_register_1 <= cpuif_req_masked and (cpuif_addr = 16#F8#);
        is_valid_addr := is_valid_addr or (cpuif_req_masked and (cpuif_addr = 16#F8#));
        is_valid_rw := is_valid_rw or (cpuif_req_masked and (cpuif_addr = 16#F8#));
        decoded_reg_strb.test_register_2 <= cpuif_req_masked and (cpuif_addr = 16#FC#);
        is_valid_addr := is_valid_addr or (cpuif_req_masked and (cpuif_addr = 16#FC#));
        is_valid_rw := is_valid_rw or (cpuif_req_masked and (cpuif_addr = 16#FC#));
        decoded_err <= (not is_valid_addr or (is_valid_addr and not is_valid_rw)) and decoded_req;
    end process;

    -- Pass down signals to next stage
    process(all) begin
        decoded_addr <= cpuif_addr;
        decoded_req <= cpuif_req_masked;
        decoded_req_is_wr <= cpuif_req_is_wr;
        decoded_wr_data <= cpuif_wr_data;
        decoded_wr_biten <= cpuif_wr_biten;
    end process;

    ----------------------------------------------------------------------------
    -- Field logic
    ----------------------------------------------------------------------------
    
    -- Field: regblock.spi_tx_data.tx_data
    process(all)
        variable next_c: std_logic_vector(7 downto 0);
        variable load_next_c: std_logic;
    begin
        next_c := field_storage.spi_tx_data.tx_data.value;
        load_next_c := '0';
        if decoded_reg_strb.spi_tx_data and decoded_req_is_wr then -- SW write
            next_c := (field_storage.spi_tx_data.tx_data.value and not decoded_wr_biten(7 downto 0)) or (decoded_wr_data(7 downto 0) and decoded_wr_biten(7 downto 0));
            load_next_c := '1';
        end if;
        field_combo.spi_tx_data.tx_data.next_q <= next_c;
        field_combo.spi_tx_data.tx_data.load_next <= load_next_c;
    end process;
    process(clk, arst) begin
        if arst then -- async reset
            field_storage.spi_tx_data.tx_data.value <= 8x"0";
        elsif rising_edge(clk) then
            if false then -- sync reset
                field_storage.spi_tx_data.tx_data.value <= 8x"0";
            else
                if field_combo.spi_tx_data.tx_data.load_next then
                    field_storage.spi_tx_data.tx_data.value <= field_combo.spi_tx_data.tx_data.next_q;
                end if;
            end if;
        end if;
    end process;
    hwif_out.spi_tx_data.tx_data.value <= field_storage.spi_tx_data.tx_data.value;

    -- Field: regblock.spi_rx_data.rx_data
    process(all)
        variable next_c: std_logic_vector(7 downto 0);
        variable load_next_c: std_logic;
    begin
        next_c := field_storage.spi_rx_data.rx_data.value;
        load_next_c := '0';
        
        -- HW Write
        next_c := hwif_in.spi_rx_data.rx_data.next_q;
        load_next_c := '1';
        field_combo.spi_rx_data.rx_data.next_q <= next_c;
        field_combo.spi_rx_data.rx_data.load_next <= load_next_c;
    end process;
    process(clk, arst) begin
        if arst then -- async reset
            field_storage.spi_rx_data.rx_data.value <= 8x"0";
        elsif rising_edge(clk) then
            if false then -- sync reset
                field_storage.spi_rx_data.rx_data.value <= 8x"0";
            else
                if field_combo.spi_rx_data.rx_data.load_next then
                    field_storage.spi_rx_data.rx_data.value <= field_combo.spi_rx_data.rx_data.next_q;
                end if;
            end if;
        end if;
    end process;
    hwif_out.spi_rx_data.rx_data.value <= field_storage.spi_rx_data.rx_data.value;

    -- Field: regblock.vga_color.blue
    process(all)
        variable next_c: std_logic_vector(3 downto 0);
        variable load_next_c: std_logic;
    begin
        next_c := field_storage.vga_color.blue.value;
        load_next_c := '0';
        if decoded_reg_strb.vga_color and decoded_req_is_wr then -- SW write
            next_c := (field_storage.vga_color.blue.value and not decoded_wr_biten(3 downto 0)) or (decoded_wr_data(3 downto 0) and decoded_wr_biten(3 downto 0));
            load_next_c := '1';
        end if;
        field_combo.vga_color.blue.next_q <= next_c;
        field_combo.vga_color.blue.load_next <= load_next_c;
    end process;
    process(clk, arst) begin
        if arst then -- async reset
            field_storage.vga_color.blue.value <= 4x"0";
        elsif rising_edge(clk) then
            if false then -- sync reset
                field_storage.vga_color.blue.value <= 4x"0";
            else
                if field_combo.vga_color.blue.load_next then
                    field_storage.vga_color.blue.value <= field_combo.vga_color.blue.next_q;
                end if;
            end if;
        end if;
    end process;
    hwif_out.vga_color.blue.value <= field_storage.vga_color.blue.value;

    -- Field: regblock.vga_color.green
    process(all)
        variable next_c: std_logic_vector(3 downto 0);
        variable load_next_c: std_logic;
    begin
        next_c := field_storage.vga_color.green.value;
        load_next_c := '0';
        if decoded_reg_strb.vga_color and decoded_req_is_wr then -- SW write
            next_c := (field_storage.vga_color.green.value and not decoded_wr_biten(7 downto 4)) or (decoded_wr_data(7 downto 4) and decoded_wr_biten(7 downto 4));
            load_next_c := '1';
        end if;
        field_combo.vga_color.green.next_q <= next_c;
        field_combo.vga_color.green.load_next <= load_next_c;
    end process;
    process(clk, arst) begin
        if arst then -- async reset
            field_storage.vga_color.green.value <= 4x"F";
        elsif rising_edge(clk) then
            if false then -- sync reset
                field_storage.vga_color.green.value <= 4x"F";
            else
                if field_combo.vga_color.green.load_next then
                    field_storage.vga_color.green.value <= field_combo.vga_color.green.next_q;
                end if;
            end if;
        end if;
    end process;
    hwif_out.vga_color.green.value <= field_storage.vga_color.green.value;

    -- Field: regblock.vga_color.red
    process(all)
        variable next_c: std_logic_vector(3 downto 0);
        variable load_next_c: std_logic;
    begin
        next_c := field_storage.vga_color.red.value;
        load_next_c := '0';
        if decoded_reg_strb.vga_color and decoded_req_is_wr then -- SW write
            next_c := (field_storage.vga_color.red.value and not decoded_wr_biten(11 downto 8)) or (decoded_wr_data(11 downto 8) and decoded_wr_biten(11 downto 8));
            load_next_c := '1';
        end if;
        field_combo.vga_color.red.next_q <= next_c;
        field_combo.vga_color.red.load_next <= load_next_c;
    end process;
    process(clk, arst) begin
        if arst then -- async reset
            field_storage.vga_color.red.value <= 4x"0";
        elsif rising_edge(clk) then
            if false then -- sync reset
                field_storage.vga_color.red.value <= 4x"0";
            else
                if field_combo.vga_color.red.load_next then
                    field_storage.vga_color.red.value <= field_combo.vga_color.red.next_q;
                end if;
            end if;
        end if;
    end process;
    hwif_out.vga_color.red.value <= field_storage.vga_color.red.value;

    -- Field: regblock.bad_address_counter.count
    process(all)
        variable next_c: std_logic_vector(31 downto 0);
        variable load_next_c: std_logic;
    begin
        next_c := field_storage.bad_address_counter.count.value;
        load_next_c := '0';
        
        -- HW Write
        next_c := hwif_in.bad_address_counter.count.next_q;
        load_next_c := '1';
        if hwif_in.bad_address_counter.count.incr then -- increment
            field_combo.bad_address_counter.count.overflow <= to_std_logic((to_unsigned("0" & next_c) + to_unsigned(33x"1")) > to_unsigned(34x"FFFFFFFF"));
            next_c := to_std_logic_vector(to_unsigned(next_c) + to_unsigned(32x"1"));
            load_next_c := '1';
        else
            field_combo.bad_address_counter.count.overflow <= '0';
        end if;
        field_combo.bad_address_counter.count.incrthreshold <= to_std_logic(unsigned(field_storage.bad_address_counter.count.value) >= to_unsigned(32x"FFFFFFFF"));
        field_combo.bad_address_counter.count.next_q <= next_c;
        field_combo.bad_address_counter.count.load_next <= load_next_c;
    end process;
    process(clk, arst) begin
        if arst then -- async reset
            field_storage.bad_address_counter.count.value <= 32x"0";
        elsif rising_edge(clk) then
            if false then -- sync reset
                field_storage.bad_address_counter.count.value <= 32x"0";
            else
                if field_combo.bad_address_counter.count.load_next then
                    field_storage.bad_address_counter.count.value <= field_combo.bad_address_counter.count.next_q;
                end if;
            end if;
        end if;
    end process;
    hwif_out.bad_address_counter.count.value <= field_storage.bad_address_counter.count.value;

    -- Field: regblock.test_register_1.test_bits
    process(all)
        variable next_c: std_logic_vector(31 downto 0);
        variable load_next_c: std_logic;
    begin
        next_c := field_storage.test_register_1.test_bits.value;
        load_next_c := '0';
        if decoded_reg_strb.test_register_1 and decoded_req_is_wr then -- SW write
            next_c := (field_storage.test_register_1.test_bits.value and not decoded_wr_biten(31 downto 0)) or (decoded_wr_data(31 downto 0) and decoded_wr_biten(31 downto 0));
            load_next_c := '1';
        end if;
        field_combo.test_register_1.test_bits.next_q <= next_c;
        field_combo.test_register_1.test_bits.load_next <= load_next_c;
    end process;
    process(clk, arst) begin
        if arst then -- async reset
            field_storage.test_register_1.test_bits.value <= 32x"0";
        elsif rising_edge(clk) then
            if false then -- sync reset
                field_storage.test_register_1.test_bits.value <= 32x"0";
            else
                if field_combo.test_register_1.test_bits.load_next then
                    field_storage.test_register_1.test_bits.value <= field_combo.test_register_1.test_bits.next_q;
                end if;
            end if;
        end if;
    end process;

    -- Field: regblock.test_register_2.test_bits
    process(all)
        variable next_c: std_logic_vector(31 downto 0);
        variable load_next_c: std_logic;
    begin
        next_c := field_storage.test_register_2.test_bits.value;
        load_next_c := '0';
        if decoded_reg_strb.test_register_2 and decoded_req_is_wr then -- SW write
            next_c := (field_storage.test_register_2.test_bits.value and not decoded_wr_biten(31 downto 0)) or (decoded_wr_data(31 downto 0) and decoded_wr_biten(31 downto 0));
            load_next_c := '1';
        end if;
        field_combo.test_register_2.test_bits.next_q <= next_c;
        field_combo.test_register_2.test_bits.load_next <= load_next_c;
    end process;
    process(clk, arst) begin
        if arst then -- async reset
            field_storage.test_register_2.test_bits.value <= 32x"0";
        elsif rising_edge(clk) then
            if false then -- sync reset
                field_storage.test_register_2.test_bits.value <= 32x"0";
            else
                if field_combo.test_register_2.test_bits.load_next then
                    field_storage.test_register_2.test_bits.value <= field_combo.test_register_2.test_bits.next_q;
                end if;
            end if;
        end if;
    end process;

    ----------------------------------------------------------------------------
    -- Write response
    ----------------------------------------------------------------------------
    cpuif_wr_ack <= decoded_req and decoded_req_is_wr;
    cpuif_wr_err <= decoded_err;

    ----------------------------------------------------------------------------
    -- Readback
    ----------------------------------------------------------------------------
    rd_mux_addr <= unsigned(decoded_addr);

    process(all)
        variable readback_data_var : std_logic_vector(31 downto 0);
    begin
        readback_data_var := (others => '0');
        if rd_mux_addr = 16#0# then
            readback_data_var(31 downto 0) := hwif_in.git_hash.hash.next_q;
        end if;
        if rd_mux_addr = 16#4# then
            readback_data_var(0) := hwif_in.git_status.status.next_q;
        end if;
        if rd_mux_addr = 16#8# then
            readback_data_var(31 downto 0) := hwif_in.fpga_id.id.next_q;
        end if;
        if rd_mux_addr = 16#C# then
            readback_data_var(7 downto 0) := field_storage.spi_tx_data.tx_data.value;
        end if;
        if rd_mux_addr = 16#10# then
            readback_data_var(7 downto 0) := field_storage.spi_rx_data.rx_data.value;
        end if;
        if rd_mux_addr = 16#14# then
            readback_data_var(3 downto 0) := field_storage.vga_color.blue.value;
            readback_data_var(7 downto 4) := field_storage.vga_color.green.value;
            readback_data_var(11 downto 8) := field_storage.vga_color.red.value;
        end if;
        if rd_mux_addr = 16#18# then
            readback_data_var(0) := hwif_in.switch_status.switch_0.next_q;
            readback_data_var(1) := hwif_in.switch_status.switch_1.next_q;
            readback_data_var(2) := hwif_in.switch_status.switch_2.next_q;
        end if;
        if rd_mux_addr = 16#1C# then
            readback_data_var(31 downto 0) := field_storage.bad_address_counter.count.value;
        end if;
        if rd_mux_addr = 16#F8# then
            readback_data_var(31 downto 0) := field_storage.test_register_1.test_bits.value;
        end if;
        if rd_mux_addr = 16#FC# then
            readback_data_var(31 downto 0) := field_storage.test_register_2.test_bits.value;
        end if;
        readback_data <= readback_data_var;
        readback_done <= decoded_req and not decoded_req_is_wr;
        readback_err <= decoded_err;
    end process;

    cpuif_rd_ack <= readback_done;
    cpuif_rd_data <= readback_data;
    cpuif_rd_err <= readback_err;
end architecture rtl;
